on:
  schedule:
    - cron: '0 * * * *'
name: Update gist with latest reads
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: update-gist
        uses: amorriscode/book-box@master
        env:
          GIST_ID: ${{ secrets.GIST_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GOODREADS_KEY: ${{ secrets.GOODREADS_KEY }}
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}